# Generated by Django 3.1.2 on 2020-11-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id_developer', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('valor_Total', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=45)),
                ('Fecha_Publicacion', models.DateField()),
                ('Precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('Texto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Correo', models.CharField(max_length=100, unique=True)),
                ('Nickname', models.CharField(max_length=100, unique=True)),
                ('Clave', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
                ('id_idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id_resena', models.IntegerField(primary_key=True, serialize=False)),
                ('Texto', models.TextField()),
                ('Correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.juego')),
                ('id_valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.valoracion')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_juego',
            fields=[
                ('id_factura_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Valor', models.FloatField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.factura')),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.juego')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario'),
        ),
        migrations.CreateModel(
            name='juegos_tiene_idiomas',
            fields=[
                ('id_juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tienda.juego')),
                ('id_idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='juegos_tiene_developers',
            fields=[
                ('id_juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tienda.juego')),
                ('id_developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.developer')),
            ],
        ),
        migrations.CreateModel(
            name='juegos_tiene_categorias',
            fields=[
                ('id_juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tienda.juego')),
                ('id_categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
        ),
    ]
